include("gherkin/feature_test.jl")
include("gherkin/scenario_test.jl")
include("gherkin/scenario_outline_test.jl")
include("gherkin/scenario_descriptions_test.jl")
include("gherkin/tag_test.jl")
include("gherkin/data_tables_test.jl")

include("selection/tag_selection_test.jl")

include("executor_test.jl")
include("executor_presentation_test.jl")
include("executor_feature_test.jl")
include("step_def_test.jl")
include("result_accumulator_test.jl")
include("asserts_test.jl")
include("outlines_test.jl")
include("exec_env_test.jl")
include("variables_test.jl")
include("suggestion_test.jl")